[build]
  publish = "."

[[redirects]]
  from = "/"
  to = "/EXP1.1/EXP1.1.html"
  status = 200

[[redirects]]
  from = "/exp1.2"
  to = "/EXP1.2/EXP1.2.html"
  status = 200

[[redirects]]
  from = "/exp1.3"
  to = "/EXP1.3/EXP1.3.html"
  status = 200
