[build]
  publish = "."

[[redirects]]
  from = "/"
  to = "/exp1.1/1.1.html"
  status = 200

[[redirects]]
  from = "/EXP1.2.1"
  to = "/EXP1.1/1.3.1.html"
  status = 200

[[redirects]]
  from = "/EXP1.3.2"
  to = "/EXP1.2/1.3.2.html"
  status = 200

[[redirects]]
  from = "/EXP1.3.3"
  to = "/EXP1.3/1.3.3.html"
  status = 200
